services:
  - type: web
    name: Relatorios-de-Engenharia-GSTE
    runtime: static
    repo: https://github.com/lookciano/Relatorios-de-Engenharia-GSTE
    branch: main
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html